INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlState`, `mdlClass`) VALUES ('Acceso', '', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Accesos', 'Control de Accesos', 'Access Control', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Tipo', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Tipos', 'Tipo de Usuarios', 'User Types', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Statuses', 'Tipos de Estado de Ordenes', 'Order Status Types', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Pago', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlState`, `mdlClass`) VALUES ('Pagos', 'Tipos de Pagos', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Categoria', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Categorias', 'Tipos de Categorias', 'Types of Categories', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Modulo', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Modulos', 'Control de Modulos', 'Modules Control', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Status', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Start', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('store', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('cart', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('storeL', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('cartL', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Variations', 'Tipo de Variaciones ', 'Variations Types', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Variation', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Productos', 'Control de Inventario', 'Inventory Managment', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Producto', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('User', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Users', 'Control de Usuarios', 'Users Management', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Roles', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Entregas', 'Control de Lugares de Entrega', 'Delivery Places Management', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Entrega', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Checkout', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Manejos', 'Control de Horarios', 'Schedule Management', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Manejo', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Historial', 'Mis Ordenes', 'My Ordes', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Ordenes', 'Manejo de Ordenes', 'Orders Management', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Orden', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Config', 'Configuración de Usuario', 'User Configuration', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Change', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Directions', 'Mis Direcciones', 'My Directions', 'ACT', 'MNU');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Approved', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Canceled', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('forgot', 'ACT', 'PGE');
INSERT INTO `psjb_db`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('pwsd', 'ACT', 'PGE');

